FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

# Copy application code
COPY model_api.py .
COPY Lung_Cancer_preprocessing/ ./Lung_Cancer_preprocessing/

# Expose the port the app runs on
EXPOSE 8000

# Command to run the app
CMD ["python", "model_api.py"]
