version: '3'

services:
  model-server:
    image: yaqin7/lung-cancer-model:latest # You can specify a specific tag if needed
    ports:
      - '8080:8080' # Default MLflow model server port
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8000:8000'
    environment:
      - MODEL_SERVER_URL=http://model-server:8080
    depends_on:
      - model-server
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=yaqin77
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  grafana-storage:
